<?php 


if (function_exists('acf_add_local_field_group')) {

    acf_add_local_field_group(array(
    'key' => 'group_69944a2c22d00',
    'title' => __('Öppettider', 'modularity-opening-hours'),
    'fields' => array(
        0 => array(
            'key' => 'field_69ce1de199e6c',
            'label' => __('Innehåll', 'modularity-opening-hours'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        1 => array(
            'key' => 'field_highlight_today_0001',
            'label' => __('Visa dagens öppettider', 'modularity-opening-hours'),
            'name' => 'highlight_today',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Visa en sammanfattning av dagens öppettider ovanför kalendern.', 'modularity-opening-hours'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => __('Ja', 'modularity-opening-hours'),
            'ui_off_text' => __('Nej', 'modularity-opening-hours'),
        ),
        2 => array(
            'key' => 'field_show_tomorrow_0001',
            'label' => __('Visa även morgondagen', 'modularity-opening-hours'),
            'name' => 'show_tomorrow_highlight',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Visa två dagar sida vid sida (idag och morgondagen).', 'modularity-opening-hours'),
            'required' => 0,
            'conditional_logic' => array(
                0 => array(
                    0 => array(
                        'field' => 'field_highlight_today_0001',
                        'operator' => '==',
                        'value' => '1',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => __('Ja', 'modularity-opening-hours'),
            'ui_off_text' => __('Nej', 'modularity-opening-hours'),
        ),
        3 => array(
            'key' => 'field_69944a2d44994',
            'label' => __('Vecka', 'modularity-opening-hours'),
            'name' => 'week_repeater',
            'aria-label' => '',
            'type' => 'repeater',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'acfe_repeater_stylised_button' => 0,
            'layout' => 'block',
            'pagination' => 0,
            'min' => 0,
            'max' => 0,
            'collapsed' => '',
            'button_label' => __('Lägg till vecka', 'modularity-opening-hours'),
            'rows_per_page' => 20,
            'sub_fields' => array(
                0 => array(
                    'key' => 'field_69945c794499a',
                    'label' => __('Veckonummer (från)', 'modularity-opening-hours'),
                    'name' => 'week_no_from',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 1,
                    'max' => 53,
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                1 => array(
                    'key' => 'field_69947962de62a',
                    'label' => __('Veckonummer (till)', 'modularity-opening-hours'),
                    'name' => 'week_no_to',
                    'aria-label' => '',
                    'type' => 'number',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'min' => 1,
                    'max' => 53,
                    'placeholder' => '',
                    'step' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                2 => array(
                    'key' => 'field_schedule_mode_0001',
                    'label' => __('Schema-läge', 'modularity-opening-hours'),
                    'name' => 'schedule_mode',
                    'aria-label' => '',
                    'type' => 'button_group',
                    'instructions' => __('Standard grupperar mån-fre. Granulärt låter dig ställa in varje veckodag individuellt.', 'modularity-opening-hours'),
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'choices' => array(
                        'standard' => __('Standard', 'modularity-opening-hours'),
                        'granular' => __('Granulärt', 'modularity-opening-hours'),
                    ),
                    'default_value' => __('standard', 'modularity-opening-hours'),
                    'return_format' => 'value',
                    'allow_null' => 1,
                    'layout' => 'horizontal',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                3 => array(
                    'key' => 'field_69944a6544995',
                    'label' => __('Öppnar (mån-fre)', 'modularity-opening-hours'),
                    'name' => 'opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                4 => array(
                    'key' => 'field_69945b7944996',
                    'label' => __('Stänger (mån-fre)', 'modularity-opening-hours'),
                    'name' => 'closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                5 => array(
                    'key' => 'field_69945bb444997',
                    'label' => __('Stängt lördag', 'modularity-opening-hours'),
                    'name' => 'closed_saturday',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                6 => array(
                    'key' => 'field_69945cf74499d',
                    'label' => __('Öppnar lördag', 'modularity-opening-hours'),
                    'name' => 'opens_saturday',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                            1 => array(
                                'field' => 'field_69945bb444997',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                7 => array(
                    'key' => 'field_69945d234499e',
                    'label' => __('Stänger lördag', 'modularity-opening-hours'),
                    'name' => 'closes_saturday_',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                            1 => array(
                                'field' => 'field_69945bb444997',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                8 => array(
                    'key' => 'field_69945bd644998',
                    'label' => __('Stängt söndag', 'modularity-opening-hours'),
                    'name' => 'closed_sunday',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '100',
                        'class' => '',
                        'id' => '',
                    ),
                    'message' => '',
                    'default_value' => 1,
                    'ui' => 0,
                    'ui_on_text' => '',
                    'ui_off_text' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                9 => array(
                    'key' => 'field_69945cac4499b',
                    'label' => __('Öppnar söndag', 'modularity-opening-hours'),
                    'name' => 'opens_sunday',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                            1 => array(
                                'field' => 'field_69945bd644998',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                10 => array(
                    'key' => 'field_69945cc64499c',
                    'label' => __('Stänger söndag', 'modularity-opening-hours'),
                    'name' => 'closes_sunday',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '!=',
                                'value' => 'granular',
                            ),
                            1 => array(
                                'field' => 'field_69945bd644998',
                                'operator' => '!=',
                                'value' => '1',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '50',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                11 => array(
                    'key' => 'field_gran_monday',
                    'label' => __('Måndag', 'modularity-opening-hours'),
                    'name' => 'monday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                12 => array(
                    'key' => 'field_gran_monday_opens',
                    'label' => __('Måndag öppnar', 'modularity-opening-hours'),
                    'name' => 'monday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                13 => array(
                    'key' => 'field_gran_monday_closes',
                    'label' => __('Måndag stänger', 'modularity-opening-hours'),
                    'name' => 'monday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                14 => array(
                    'key' => 'field_gran_monday_desc',
                    'label' => __('Beskrivning (måndag)', 'modularity-opening-hours'),
                    'name' => 'monday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                15 => array(
                    'key' => 'field_gran_tuesday',
                    'label' => __('Tisdag', 'modularity-opening-hours'),
                    'name' => 'tuesday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                16 => array(
                    'key' => 'field_gran_tuesday_opens',
                    'label' => __('Tisdag öppnar', 'modularity-opening-hours'),
                    'name' => 'tuesday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                17 => array(
                    'key' => 'field_gran_tuesday_closes',
                    'label' => __('Tisdag stänger', 'modularity-opening-hours'),
                    'name' => 'tuesday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                18 => array(
                    'key' => 'field_gran_tuesday_desc',
                    'label' => __('Beskrivning (tisdag)', 'modularity-opening-hours'),
                    'name' => 'tuesday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                19 => array(
                    'key' => 'field_gran_wednesday',
                    'label' => __('Onsdag', 'modularity-opening-hours'),
                    'name' => 'wednesday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                20 => array(
                    'key' => 'field_gran_wednesday_opens',
                    'label' => __('Onsdag öppnar', 'modularity-opening-hours'),
                    'name' => 'wednesday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                21 => array(
                    'key' => 'field_gran_wednesday_closes',
                    'label' => __('Onsdag stänger', 'modularity-opening-hours'),
                    'name' => 'wednesday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                22 => array(
                    'key' => 'field_gran_wednesday_desc',
                    'label' => __('Beskrivning (onsdag)', 'modularity-opening-hours'),
                    'name' => 'wednesday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                23 => array(
                    'key' => 'field_gran_thursday',
                    'label' => __('Torsdag', 'modularity-opening-hours'),
                    'name' => 'thursday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                24 => array(
                    'key' => 'field_gran_thursday_opens',
                    'label' => __('Torsdag öppnar', 'modularity-opening-hours'),
                    'name' => 'thursday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                25 => array(
                    'key' => 'field_gran_thursday_closes',
                    'label' => __('Torsdag stänger', 'modularity-opening-hours'),
                    'name' => 'thursday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                26 => array(
                    'key' => 'field_gran_thursday_desc',
                    'label' => __('Beskrivning (torsdag)', 'modularity-opening-hours'),
                    'name' => 'thursday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                27 => array(
                    'key' => 'field_gran_friday',
                    'label' => __('Fredag', 'modularity-opening-hours'),
                    'name' => 'friday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 0,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                28 => array(
                    'key' => 'field_gran_friday_opens',
                    'label' => __('Fredag öppnar', 'modularity-opening-hours'),
                    'name' => 'friday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                29 => array(
                    'key' => 'field_gran_friday_closes',
                    'label' => __('Fredag stänger', 'modularity-opening-hours'),
                    'name' => 'friday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                30 => array(
                    'key' => 'field_gran_friday_desc',
                    'label' => __('Beskrivning (fredag)', 'modularity-opening-hours'),
                    'name' => 'friday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                31 => array(
                    'key' => 'field_gran_saturday',
                    'label' => __('Lördag', 'modularity-opening-hours'),
                    'name' => 'saturday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                32 => array(
                    'key' => 'field_gran_saturday_opens',
                    'label' => __('Lördag öppnar', 'modularity-opening-hours'),
                    'name' => 'saturday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                33 => array(
                    'key' => 'field_gran_saturday_closes',
                    'label' => __('Lördag stänger', 'modularity-opening-hours'),
                    'name' => 'saturday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                34 => array(
                    'key' => 'field_gran_saturday_desc',
                    'label' => __('Beskrivning (lördag)', 'modularity-opening-hours'),
                    'name' => 'saturday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                35 => array(
                    'key' => 'field_gran_sunday',
                    'label' => __('Söndag', 'modularity-opening-hours'),
                    'name' => 'sunday_is_closed',
                    'aria-label' => '',
                    'type' => 'true_false',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => 1,
                    'ui' => 1,
                    'ui_on_text' => __('Stängt', 'modularity-opening-hours'),
                    'ui_off_text' => __('Öppen', 'modularity-opening-hours'),
                    'parent_repeater' => 'field_69944a2d44994',
                    'message' => '',
                ),
                36 => array(
                    'key' => 'field_gran_sunday_opens',
                    'label' => __('Söndag öppnar', 'modularity-opening-hours'),
                    'name' => 'sunday_opens',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                37 => array(
                    'key' => 'field_gran_sunday_closes',
                    'label' => __('Söndag stänger', 'modularity-opening-hours'),
                    'name' => 'sunday_closes',
                    'aria-label' => '',
                    'type' => 'time_picker',
                    'instructions' => '',
                    'required' => false,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'display_format' => 'H:i:s',
                    'return_format' => 'H:i:s',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                38 => array(
                    'key' => 'field_gran_sunday_desc',
                    'label' => __('Beskrivning (söndag)', 'modularity-opening-hours'),
                    'name' => 'sunday_description',
                    'aria-label' => '',
                    'type' => 'text',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => array(
                        0 => array(
                            0 => array(
                                'field' => 'field_schedule_mode_0001',
                                'operator' => '==',
                                'value' => 'granular',
                            ),
                        ),
                    ),
                    'wrapper' => array(
                        'width' => '25',
                        'class' => '',
                        'id' => '',
                    ),
                    'default_value' => '',
                    'maxlength' => '',
                    'placeholder' => '',
                    'prepend' => '',
                    'append' => '',
                    'parent_repeater' => 'field_69944a2d44994',
                ),
                39 => array(
                    'key' => 'field_69945be944999',
                    'label' => __('Avvikande öppettider', 'modularity-opening-hours'),
                    'name' => 'special_opening_hours',
                    'aria-label' => '',
                    'type' => 'repeater',
                    'instructions' => '',
                    'required' => 0,
                    'conditional_logic' => 0,
                    'wrapper' => array(
                        'width' => '',
                        'class' => '',
                        'id' => '',
                    ),
                    'acfe_repeater_stylised_button' => 0,
                    'layout' => 'block',
                    'min' => 0,
                    'max' => 0,
                    'collapsed' => '',
                    'button_label' => __('Lägg till rad', 'modularity-opening-hours'),
                    'rows_per_page' => 20,
                    'sub_fields' => array(
                        0 => array(
                            'key' => 'field_6994600753009',
                            'label' => __('Veckodag', 'modularity-opening-hours'),
                            'name' => 'special_opening_date',
                            'aria-label' => '',
                            'type' => 'date_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'd/m/Y',
                            'return_format' => 'd/m/Y',
                            'first_day' => 1,
                            'parent_repeater' => 'field_69945be944999',
                        ),
                        1 => array(
                            'key' => 'field_6994604a5300a',
                            'label' => __('Öppnar denna dagen', 'modularity-opening-hours'),
                            'name' => 'opens_this_day',
                            'aria-label' => '',
                            'type' => 'time_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'H:i:s',
                            'return_format' => 'H:i:s',
                            'parent_repeater' => 'field_69945be944999',
                        ),
                        2 => array(
                            'key' => 'field_699460605300b',
                            'label' => __('Stänger denna dagen', 'modularity-opening-hours'),
                            'name' => 'closes_this_day',
                            'aria-label' => '',
                            'type' => 'time_picker',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'display_format' => 'H:i:s',
                            'return_format' => 'H:i:s',
                            'parent_repeater' => 'field_69945be944999',
                        ),
                        3 => array(
                            'key' => 'field_69d664a65069e',
                            'label' => __('Beskrivning', 'modularity-opening-hours'),
                            'name' => 'special_opening_hours_description',
                            'aria-label' => '',
                            'type' => 'text',
                            'instructions' => '',
                            'required' => 0,
                            'conditional_logic' => 0,
                            'wrapper' => array(
                                'width' => '',
                                'class' => '',
                                'id' => '',
                            ),
                            'default_value' => '',
                            'maxlength' => '',
                            'placeholder' => '',
                            'prepend' => '',
                            'append' => '',
                            'parent_repeater' => 'field_69945be944999',
                        ),
                    ),
                    'parent_repeater' => 'field_69944a2d44994',
                ),
            ),
        ),
        4 => array(
            'key' => 'field_69ce1e0f99e6d',
            'label' => __('Utseende', 'modularity-opening-hours'),
            'name' => '',
            'aria-label' => '',
            'type' => 'tab',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'placement' => 'top',
            'endpoint' => 0,
            'selected' => 0,
        ),
        5 => array(
            'key' => 'field_69ce1e2199e6e',
            'label' => __('Utseende för pagineringsknapp', 'modularity-opening-hours'),
            'name' => 'pagination_btn_style',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'text' => __('Text', 'modularity-opening-hours'),
                'icon' => __('Ikon', 'modularity-opening-hours'),
            ),
            'default_value' => __('text', 'modularity-opening-hours'),
            'return_format' => 'value',
            'allow_null' => 0,
            'layout' => 'horizontal',
        ),
        6 => array(
            'key' => 'field_69ce1e7499e6f',
            'label' => __('Visa år', 'modularity-opening-hours'),
            'name' => 'show_year',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        7 => array(
            'key' => 'field_69ce1e8999e70',
            'label' => __('Visa veckodatum', 'modularity-opening-hours'),
            'name' => 'show_week_dates',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '50',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 1,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        8 => array(
            'key' => 'field_69f8a1b2c3d4e',
            'label' => __('Visa veckonummer i paginering', 'modularity-opening-hours'),
            'name' => 'show_week_no_in_paging',
            'aria-label' => '',
            'type' => 'true_false',
            'instructions' => __('Visar grannveckors veckonummer med aktuell vecka i fetstil (t.ex. 22 23 24).', 'modularity-opening-hours'),
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'message' => '',
            'default_value' => 0,
            'ui' => 1,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        9 => array(
            'key' => 'field_69d66902845ad',
            'label' => __('Bakgrundsfärg', 'modularity-opening-hours'),
            'name' => 'background_color',
            'aria-label' => '',
            'type' => 'color_picker',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'default_value' => __('#cadfde', 'modularity-opening-hours'),
            'enable_opacity' => 0,
            'return_format' => 'string',
        ),
        10 => array(
            'key' => 'field_69d7981b27625',
            'label' => __('Textfärg', 'modularity-opening-hours'),
            'name' => 'text_color',
            'aria-label' => '',
            'type' => 'button_group',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '',
                'class' => '',
                'id' => '',
            ),
            'choices' => array(
                'white' => __('Vit', 'modularity-opening-hours'),
                'black' => __('Svart', 'modularity-opening-hours'),
            ),
            'default_value' => __('black', 'modularity-opening-hours'),
            'return_format' => 'value',
            'allow_null' => 0,
            'layout' => 'horizontal',
        ),
    ),
    'location' => array(
        0 => array(
            0 => array(
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'mod-opening-hours',
            ),
        ),
        1 => array(
            0 => array(
                'param' => 'block',
                'operator' => '==',
                'value' => 'acf/opening-hours',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'left',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
    'show_in_rest' => 0,
    'acfe_display_title' => '',
    'acfe_autosync' => array(
        0 => 'php',
        1 => 'json',
    ),
    'acfe_form' => 0,
    'acfe_meta' => '',
    'acfe_note' => '',
));

}