<?php
add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_69944a2c22d00',
	'title' => 'Opening Hours',
	'fields' => array(
		array(
			'key' => 'field_69944a2d44994',
			'label' => __( 'Week', 'modularity-opening-hours' ),
			'name' => 'week_repeater',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'table',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => __( 'Lägg till rad', 'modularity-opening-hours' ),
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69945c794499a',
					'label' => __( 'Week no.', 'modularity-opening-hours' ),
					'name' => 'week_no',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 1,
					'max' => 53,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69944a6544995',
					'label' => __( 'Opens (Mon-Fri)', 'modularity-opening-hours' ),
					'name' => 'opens',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945b7944996',
					'label' => __( 'Closes (Mon-Fri)', 'modularity-opening-hours' ),
					'name' => 'closes',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945bb444997',
					'label' => __( 'Closed Saturday', 'modularity-opening-hours' ),
					'name' => 'closed_saturday',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cf74499d',
					'label' => __( 'Opens Saturday', 'modularity-opening-hours' ),
					'name' => 'opens_saturday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69945bb444997',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945d234499e',
					'label' => __( 'Closes Saturday', 'modularity-opening-hours' ),
					'name' => 'closes_saturday_',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69945bb444997',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945bd644998',
					'label' => __( 'Closed Sunday', 'modularity-opening-hours' ),
					'name' => 'closed_sunday',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cac4499b',
					'label' => __( 'Opens Sunday', 'modularity-opening-hours' ),
					'name' => 'opens_sunday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69945bd644998',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cc64499c',
					'label' => __( 'Closes Sunday', 'modularity-opening-hours' ),
					'name' => 'closes_sunday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_69945bd644998',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'g:i a',
					'return_format' => 'g:i a',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945be944999',
					'label' => __( 'Special opening hours this week', 'modularity-opening-hours' ),
					'name' => 'special_opening_hours_this_week',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'table',
					'pagination' => 0,
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => __( 'Lägg till rad', 'modularity-opening-hours' ),
					'rows_per_page' => 20,
					'sub_fields' => array(
					),
					'parent_repeater' => 'field_69944a2d44994',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'mod-opening-hours',
			),
		),
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/opening-hours',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
) );
} );

