<?php

if (!defined('ABSPATH')) {
    exit;
}
	acf_add_local_field_group( array(
	'key' => 'group_69944a2c22d00',
	'title' => 'Öppettider',
	'fields' => array(
		array(
			'key' => 'field_highlight_today_0001',
			'label' => 'Visa dagens öppettider',
			'name' => 'highlight_today',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Visa en sammanfattning av dagens öppettider ovanför kalendern.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nej',
		),
		array(
			'key' => 'field_show_tomorrow_0001',
			'label' => 'Visa även morgondagen',
			'name' => 'show_tomorrow_highlight',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Visa två dagar sida vid sida (idag och morgondagen).',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_highlight_today_0001',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => 'Ja',
			'ui_off_text' => 'Nej',
		),
		array(
			'key' => 'field_69944a2d44994',
			'label' => 'Vecka',
			'name' => 'week_repeater',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 0,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Lägg till vecka',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_69945c794499a',
					'label' => 'Veckonummer (från)',
					'name' => 'week_no_from',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 1,
					'max' => 53,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69947962de62a',
					'label' => 'Veckonummer (till)',
					'name' => 'week_no_to',
					'aria-label' => '',
					'type' => 'number',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'min' => 1,
					'max' => 53,
					'placeholder' => '',
					'step' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_schedule_mode_0001',
					'label' => 'Schema-läge',
					'name' => 'schedule_mode',
					'aria-label' => '',
					'type' => 'button_group',
					'instructions' => 'Standard grupperar mån-fre. Granulärt låter dig ställa in varje veckodag individuellt.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'standard' => 'Standard',
						'granular' => 'Granulärt',
					),
					'default_value' => 'standard',
					'return_format' => 'value',
					'allow_null' => 1,
					'layout' => 'horizontal',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69944a6544995',
					'label' => 'Öppnar (mån-fre)',
					'name' => 'opens',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945b7944996',
					'label' => 'Stänger (mån-fre)',
					'name' => 'closes',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945bb444997',
					'label' => 'Stängt lördag',
					'name' => 'closed_saturday',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
						),
					),
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cf74499d',
					'label' => 'Öppnar lördag',
					'name' => 'opens_saturday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
							array(
								'field' => 'field_69945bb444997',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945d234499e',
					'label' => 'Stänger lördag',
					'name' => 'closes_saturday_',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
							array(
								'field' => 'field_69945bb444997',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945bd644998',
					'label' => 'Stängt söndag',
					'name' => 'closed_sunday',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
						),
					),
					'wrapper' => array(
						'width' => '100',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cac4499b',
					'label' => 'Öppnar söndag',
					'name' => 'opens_sunday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
							array(
								'field' => 'field_69945bd644998',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945cc64499c',
					'label' => 'Stänger söndag',
					'name' => 'closes_sunday',
					'aria-label' => '',
					'type' => 'time_picker',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_schedule_mode_0001',
								'operator' => '!=',
								'value' => 'granular',
							),
							array(
								'field' => 'field_69945bd644998',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_monday',
					'label' => 'Måndag',
					'name' => 'monday_is_closed',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_monday_opens',
					'label' => 'Måndag öppnar',
					'name' => 'monday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_monday_closes',
					'label' => 'Måndag stänger',
					'name' => 'monday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_tuesday',
					'label' => 'Tisdag',
					'name' => 'tuesday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_tuesday_opens',
					'label' => 'Tisdag öppnar',
					'name' => 'tuesday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_tuesday_closes',
					'label' => 'Tisdag stänger',
					'name' => 'tuesday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_wednesday',
					'label' => 'Onsdag',
					'name' => 'wednesday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_wednesday_opens',
					'label' => 'Onsdag öppnar',
					'name' => 'wednesday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_wednesday_closes',
					'label' => 'Onsdag stänger',
					'name' => 'wednesday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_thursday',
					'label' => 'Torsdag',
					'name' => 'thursday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_thursday_opens',
					'label' => 'Torsdag öppnar',
					'name' => 'thursday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_thursday_closes',
					'label' => 'Torsdag stänger',
					'name' => 'thursday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_friday',
					'label' => 'Fredag',
					'name' => 'friday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 0,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_friday_opens',
					'label' => 'Fredag öppnar',
					'name' => 'friday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_friday_closes',
					'label' => 'Fredag stänger',
					'name' => 'friday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_saturday',
					'label' => 'Lördag',
					'name' => 'saturday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_saturday_opens',
					'label' => 'Lördag öppnar',
					'name' => 'saturday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_saturday_closes',
					'label' => 'Lördag stänger',
					'name' => 'saturday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_sunday',
					'label' => 'Söndag',
					'name' => 'sunday_is_closed',
					'type' => 'true_false',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => 'Stängt',
					'ui_off_text' => 'Öppen',
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_sunday_opens',
					'label' => 'Söndag öppnar',
					'name' => 'sunday_opens',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_gran_sunday_closes',
					'label' => 'Söndag stänger',
					'name' => 'sunday_closes',
					'type' => 'time_picker',
					'display_format' => 'H:i:s',
					'return_format' => 'H:i:s',
					'conditional_logic' => array(array(array('field' => 'field_schedule_mode_0001', 'operator' => '==', 'value' => 'granular'))),
					'wrapper' => array('width' => '33', 'class' => '', 'id' => ''),
					'parent_repeater' => 'field_69944a2d44994',
				),
				array(
					'key' => 'field_69945be944999',
					'label' => 'Avvikande öppettider',
					'name' => 'special_opening_hours',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'block',
					'min' => 0,
					'max' => 0,
					'collapsed' => '',
					'button_label' => 'Lägg till rad',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_6994600753009',
							'label' => 'Veckodag',
							'name' => 'special_opening_date',
							'aria-label' => '',
							'type' => 'date_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'd/m/Y',
							'return_format' => 'd/m/Y',
							'first_day' => 1,
							'parent_repeater' => 'field_69945be944999',
						),
						array(
							'key' => 'field_6994604a5300a',
							'label' => 'Öppnar denna dagen',
							'name' => 'opens_this_day',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'H:i:s',
							'return_format' => 'H:i:s',
							'parent_repeater' => 'field_69945be944999',
						),
						array(
							'key' => 'field_699460605300b',
							'label' => 'Stänger denna dagen',
							'name' => 'closes_this_day',
							'aria-label' => '',
							'type' => 'time_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'display_format' => 'H:i:s',
							'return_format' => 'H:i:s',
							'parent_repeater' => 'field_69945be944999',
						),
					),
					'parent_repeater' => 'field_69944a2d44994',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'mod-opening-hours',
			),
		),
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/opening-hours',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => array(
		0 => 'php',
		1 => 'json',
	),
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
) );